### ISSUE TITLE
Where is simple_compression?

### ISSUE THREAD

**Issue by MichaelCurrie** [AidanRocke/behavioral_syntax#12]
When I try to run `demos/posture_sequence.py`, there is a line:

```
from simple_compression import simple_compression
```

But simple_compression is not found in this module.  What should I do?  Thanks!

**Comment by AidanRocke** [comment]
I should have fixed this a while back. The newest version of posture_sequence is discrete_models/discretization/posture_sequence.py

simple_compression is actually the function defined in discrete_models/nlp_methods/compression/time_warp.py
