### ISSUE TITLE
Repo starting point?

### ISSUE THREAD

**Issue by MichaelCurrie** [AidanRocke/behavioral_syntax#13]
I tried using `/demos/posture_sequence.py`, and `/tests/test2.py`.

Is there another starting point I should be going to?  Thanks!

**Comment by AidanRocke** [comment]
Michael, the demo is going to contain the starting point but that's something I haven't been working on seriously yet. I was wondering whether I should use ipython notebooks as the final output of the analysis of different worm postures or pdf.

Two months ago I figured that pdf was a much more common format so I think I'll go ahead and use reportlab for the output of the demos.

**Comment by MichaelCurrie** [comment]
What I mean is, what is the top-level script I should be executing, or are there multiple top-level scripts?  Thanks!

**Comment by AidanRocke** [comment]
Now I get you. There will be multiple top level scripts in the lab_reports
module.

Here's the explanation of how that will work:
http://behavioral-syntax.readthedocs.org/en/latest/lab_reports.html
The documentation is incomplete but a lot more will be added by the end of
this week.

Sincerely,

Aidan
