### ISSUE TITLE
Where are compression and metrics

### ISSUE THREAD

**Issue by MichaelCurrie** [AidanRocke/behavioral_syntax#14]
In `test2.py`, there are the lines:

```
from behavioral_syntax.compression import time_warp as tw
from behavioral_syntax.metrics import dynamic_time_warp as dtw
```

I can't find `compression` or `metrics` in this repo.

Also, to make it possible to `import behavioral_syntax` at all, I added the following line before the imports:
```
import sys
sys.path.append('../..')
```
This way I believe `test2.py` can be executed directly as a script.

**Comment by AidanRocke** [comment]
I think I can simplify the structure of this repo but right now these are located here:

from behavioral_syntax.discrete_models.nlp_methods.compression import time_warp as tw
from behavioral_syntax.utilities.metrics import dynamic_time_warp as dtw
